In [1]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('df_data.csv').dropna()

data

,Unnamed: 0,time_UTC,observed_data,forecast_data,offset,x,y,station_id,time_UTC_dt
1,0.0,9/25/2022 1:00,2.560,2.315,-0.245,-73.710194,40.866222,1302250.0,0.0
3,1.0,9/25/2022 2:00,2.540,3.625,1.085,-73.710194,40.866222,1302250.0,60.0
5,2.0,9/25/2022 3:00,2.940,3.959,1.019,-73.710194,40.866222,1302250.0,120.0
7,3.0,9/25/2022 4:00,3.270,3.747,0.477,-73.710194,40.866222,1302250.0,180.0
9,4.0,9/25/2022 5:00,2.970,2.483,-0.487,-73.710194,40.866222,1302250.0,240.0
...,...,...,...,...,...,...,...,...,...
83519,41759.0,10/1/2022 19:00,1.060,0.452,-0.608,-67.938500,18.089910,9759938.0,9720.0
83521,41760.0,10/1/2022 20:00,1.063,0.410,-0.653,-67.938500,18.089910,9759938.0,9780.0
83523,41761.0,10/1/2022 21:00,1.024,0.360,-0.664,-67.938500,18.089910,9759938.0,9840.0
83525,41762.0,10/1/2022 22:00,0.981,0.293,-0.688,-67.938500,18.089910,9759938.0,9900.0
83527,41763.0,10/1/2022 23:00,0.814,0.213,-0.601,-67.938500,18.089910,9759938.0,9960.0

In [3]:
global_mean = data['offset'].mean()
global_std = data['offset'].std()

threshold = 3 * global_std

print(threshold)

2.9219364045139575

In [4]:
def filter_outliers(df):
    station_mean = df['offset'].mean()
    return df[(df['offset'] >= station_mean - threshold) & (df['offset'] <= station_mean + threshold)]

filtered_data= data.groupby('station_id').apply(filter_outliers).reset_index(drop=True)

In [5]:
filtered_data

,Unnamed: 0,time_UTC,observed_data,forecast_data,offset,x,y,station_id,time_UTC_dt
0,3153.0,9/25/2022 1:00,0.145,-0.239,-0.384,-89.2465,29.133800,1.545000e+03,0.0
1,3154.0,9/25/2022 2:00,0.206,-0.204,-0.410,-89.2465,29.133800,1.545000e+03,60.0
2,3155.0,9/25/2022 3:00,0.276,-0.163,-0.439,-89.2465,29.133800,1.545000e+03,120.0
3,3156.0,9/25/2022 4:00,0.355,-0.118,-0.473,-89.2465,29.133800,1.545000e+03,180.0
4,3157.0,9/25/2022 5:00,0.335,-0.093,-0.428,-89.2465,29.133800,1.545000e+03,240.0
...,...,...,...,...,...,...,...,...,...
41579,17996.0,10/1/2022 19:00,4.410,4.972,0.562,-70.3817,43.461628,4.327420e+14,9720.0
41580,17997.0,10/1/2022 20:00,4.540,4.698,0.158,-70.3817,43.461628,4.327420e+14,9780.0
41581,17998.0,10/1/2022 21:00,3.760,3.339,-0.421,-70.3817,43.461628,4.327420e+14,9840.0
41582,17999.0,10/1/2022 22:00,2.030,1.235,-0.795,-70.3817,43.461628,4.327420e+14,9900.0
41583,18000.0,10/1/2022 23:00,-0.290,-1.085,-0.795,-70.3817,43.461628,4.327420e+14,9960.0

In [6]:
print(data['station_id'].nunique())
print(filtered_data['station_id'].nunique())

263
263

In [8]:
stations_dict= (filtered_data['station_id'].value_counts()).to_dict()

stations_dict

{1545.0: 167,
 8729108.0: 167,
 8720219.0: 167,
 8720357.0: 167,
 8722670.0: 167,
 8722956.0: 167,
 8723214.0: 167,
 8723970.0: 167,
 8724580.0: 167,
 8726520.0: 167,
 8726724.0: 167,
 8727520.0: 167,
 8728690.0: 167,
 8729210.0: 167,
 8720030.0: 167,
 8729840.0: 167,
 8735180.0: 167,
 8735391.0: 167,
 8736897.0: 167,
 8737048.0: 167,
 8747437.0: 167,
 8760721.0: 167,
 8760922.0: 167,
 8761305.0: 167,
 8761724.0: 167,
 8761927.0: 167,
 8720218.0: 167,
 8670870.0: 167,
 8537121.0: 167,
 8573927.0: 167,
 8540433.0: 167,
 8545240.0: 167,
 8546252.0: 167,
 8548989.0: 167,
 8551762.0: 167,
 8551910.0: 167,
 8557380.0: 167,
 8570283.0: 167,
 8571421.0: 167,
 8571892.0: 167,
 8573364.0: 167,
 8574680.0: 167,
 8658163.0: 167,
 8575512.0: 167,
 8577330.0: 167,
 8594900.0: 167,
 1670.0: 167,
 8635027.0: 167,
 8635750.0: 167,
 8637689.0: 167,
 8651370.0: 167,
 8652587.0: 167,
 8654467.0: 167,
 8656483.0: 167,
 8761955.0: 167,
 8764044.0: 167,
 8764227.0: 167,
 165258890.0: 167,
 9759394.0: 167,
 9759938.0: 167,
 21108125.0: 167,
 21720677.0: 167,
 21989715.0: 167,
 21989773.0: 167,
 73745257.0: 167,
 73745258.0: 167,
 73745275.0: 167,
 73813498.0: 167,
 73815450.0: 167,
 217206935.0: 167,
 8764314.0: 167,
 217206962.0: 167,
 219897993.0: 167,
 251127000000000.0: 167,
 251549000000000.0: 167,
 291929000000000.0: 167,
 292800000000000.0: 167,
 300722000000000.0: 167,
 301001000000000.0: 167,
 411838000000000.0: 167,
 414507000000000.0: 167,
 420259000000000.0: 167,
 9759110.0: 167,
 9752235.0: 167,
 9751639.0: 167,
 9751401.0: 167,
 8766072.0: 167,
 8768094.0: 167,
 8770475.0: 167,
 8770520.0: 167,
 8770613.0: 167,
 8770822.0: 167,
 8771013.0: 167,
 8771341.0: 167,
 8771367.0: 167,
 8771450.0: 167,
 8771486.0: 167,
 8771972.0: 167,
 8772985.0: 167,
 8773037.0: 167,
 8773767.0: 167,
 8775222.0: 167,
 8775237.0: 167,
 8775241.0: 167,
 8775244.0: 167,
 8775296.0: 167,
 8779280.0: 167,
 9751364.0: 167,
 9751381.0: 167,
 8539094.0: 167,
 8632200.0: 167,
 8536110.0: 167,
 2481270.0: 167,
 2042770.0: 167,
 2084472.0: 167,
 2110725.0: 167,
 2110802.0: 167,
 2136350.0: 167,
 2171905.0: 167,
 2172050.0: 167,
 2198920.0: 167,
 2226180.0: 167,
 8534720.0: 167,
 2231254.0: 167,
 2244040.0: 167,
 2244440.0: 167,
 2245290.0: 167,
 2245340.0: 167,
 2246500.0: 167,
 2251800.0: 167,
 2277100.0: 167,
 2277110.0: 167,
 1647600.0: 167,
 1580620.0: 167,
 1488110.0: 167,
 1309225.0: 167,
 1850.0: 167,
 73650.0: 167,
 85420.0: 167,
 85575.0: 167,
 85750.0: 167,
 1304200.0: 167,
 1304746.0: 167,
 1306402.0: 167,
 1310521.0: 167,
 1485755.0: 167,
 1311145.0: 167,
 1376269.0: 167,
 1376562.0: 167,
 1484085.0: 167,
 1484540.0: 167,
 1484683.0: 167,
 1484701.0: 167,
 1484746.0: 167,
 2299735.0: 167,
 432742000000000.0: 167,
 7374526.0: 167,
 7381600.0: 167,
 8449130.0: 167,
 7380249.0: 167,
 8447930.0: 167,
 8447435.0: 167,
 8079120.0: 167,
 7381349.0: 167,
 7387040.0: 167,
 8030540.0: 167,
 7387050.0: 167,
 8447386.0: 167,
 8443970.0: 167,
 8419870.0: 167,
 8017095.0: 167,
 8418150.0: 167,
 8452660.0: 167,
 7374527.0: 167,
 8452944.0: 167,
 8413320.0: 167,
 8531680.0: 167,
 8519483.0: 167,
 8410140.0: 167,
 8518962.0: 167,
 8518750.0: 167,
 8516945.0: 167,
 8510560.0: 167,
 8454000.0: 167,
 8467150.0: 167,
 8465705.0: 167,
 8461490.0: 167,
 8454049.0: 167,
 8774770.0: 166,
 8638901.0: 166,
 8776604.0: 166,
 1484670.0: 166,
 8778490.0: 166,
 9755371.0: 166,
 8773259.0: 166,
 8555889.0: 166,
 285531000000000.0: 166,
 301200000000000.0: 166,
 8773701.0: 166,
 2228295.0: 166,
 2110815.0: 166,
 8661070.0: 166,
 7380330.0: 166,
 8772471.0: 166,
 2231291.0: 165,
 8779749.0: 165,
 8638610.0: 165,
 2172020.0: 165,
 21720508.0: 165,
 21720709.0: 165,
 2310747.0: 165,
 8726674.0: 165,
 8726384.0: 165,
 8665530.0: 165,
 204292275.0: 164,
 2310742.0: 164,
 8720226.0: 164,
 301124000000000.0: 164,
 8775792.0: 164,
 8658120.0: 164,
 8639348.0: 163,
 1311875.0: 163,
 2299734.0: 163,
 8777812.0: 162,
 85670.0: 162,
 2310674.0: 162,
 204289994.0: 162,
 8776139.0: 161,
 2310740.0: 161,
 1670060.0: 161,
 2172053.0: 160,
 2310673.0: 157,
 2042893.0: 157,
 2171800.0: 155,
 2313272.0: 155,
 8726607.0: 154,
 8775283.0: 154,
 2043433.0: 154,
 21720869.0: 153,
 2310712.0: 152,
 8725520.0: 147,
 2310663.0: 142,
 2110777.0: 142,
 9752695.0: 142,
 8721604.0: 138,
 1484812.0: 131,
 21989792.0: 131,
 8725110.0: 89,
 251355000000000.0: 87,
 1302250.0: 84,
 2290888.0: 82,
 251115000000000.0: 80,
 250802000000000.0: 78,
 2171850.0: 55,
 8631044.0: 46,
 2306028.0: 40,
 251032000000000.0: 31,
 76010.0: 23,
 73745235.0: 23,
 1310740.0: 21,
 2310752.0: 7,
 2246621.0: 4,
 2327031.0: 4}

In [9]:
count_167 = sum(value == 167 for value in stations_dict.values())

print(f"The number of dictionary elements with value 167 is: {count_167}")

The number of dictionary elements with value 167 is: 188

In [ ]:
# filtered_data.to_csv('filtered_data_2.csv', index=False)

# print("Filtering complete. The filtered data is saved to 'filtered_data.csv'.")